# a netSEM R Script

## Roger H. French
## netSEM License: GPL >= v2
browseURL("https://www.gnu.org/licenses/gpl-3.0.en.html")

# Network Structure Equation Modeling
## Description
## The R package 'netSEM' conducts a net-SEM statistical analysis (network 
## structural equation modeling) on a dataframe of coincident observations of 
## multiple continuous variables.


# install.packages('netSEM')

  library(netSEM)

  ?netSEM

  ?netSEM-package

  ?netSEMm

# netSEMm: This function carries out netSEM

# netSEMm(x, exogenous = NULL, endogenous = NULL, nlsInits = data.frame(a1 =
## 1, a2 = 1, a3 = 1), str = FALSE)

# Arguments
# x	
## A dataframe. By default it considers all columns as exogenous variables, except ## first column which stores the system endogenous variable.
## exogenous, by defult it consideres all columns as exogenous variables except 
## ## column number 1, which is the main endogenous response.
 
# endogenous	
## A character string of the column name of the main endogenous OR a numeric number 
##indexing the column of the main endogenous.
 
# nlsInits	
## a data frame of initial vectors for nls. Each column corresponds to a 
## coefficient.
## The data frame can be generated by the genInit() function. Each row is one
##  initial vecotor. Currently the only nls function included is 
##  y = a + b * exp(c * x).

# str	
## A boolean, whether or not this is a 'strength' type problem
 
# Details
## netSEM builds a network model of multiple continuous variables. Each pair of
## variables is tested for sensible paring relation chosen from 7 pre-selected 
## common functional forms in linear regression settings. Adjusted R-squared is
## used for model selection for every pair.

## P-values reported in the "res.print" field of the return list contains the 
## P-values of estimators of linear regression coefficients. The P-values are 
## ordered in the common order of coefficients, i.e. in the order of increasing
## exponents. For example, in the quadratic functional form 
## y ~ b0 + b1x + b2x^2, the three P-values correspond two those of \hatb0, 
## \hatb1 and \hatb2, respectively. If there are less than 3 coefficients to 
## estimate, the extra P-value field is filled with NA's.

# Value

# An object of class netSEM, which is a list of the following items:
 
## "table": A matrix. For each row, first column is the endogenous variable,
## second column is the predictor, the other columns show corresponding summary
## information: Best functional form, R-squared, adj-R-squared, P-value1, P
## -value2 and P-value3. The P-values correspond to those of estimators of
## linear regression coefficients. See details.

## "bestModels": A matrix. First dimension indicates predictors. The second 
## dimension indicates endogenous variables. The i-jth cell of the matrix 
## stores the name of the best functional form corresponding to the j-th 
## endogenous variable regressed on the i-th predictor.

## "allModels": A three dimensional list. The first dimension indicates 
## predictors. The second dimension indicates endogenous variables. Third 
## dimension indicates the fitting results of all 6 functional forms. The 
## i-j-k-th cell of the list stores a "lm" object, corresponding to the j-th 
## endogenous, i-th predictor and the k-th functional form.
 
# The object has two added attributes:
 
## "attr(res.best, "Step")": A vector. For each variable, it shows in which 
## step it is choosen to be significantly related to endogenous variable.

## "attr(res.best, "diag.Step")": A matrix. First dimension is predictors; 
## second dimension is endogenous variables. Each cell shows in which step the 
## pairwise relation is being fitted.

#======================================================================
# Acrylic Example

# First lets clar our environment so that our moels don't get mixed

  rm(list = ls())

## Load the sample acrylic data set

  data(acrylic)
  
  str(acrylic)
  
  head(acrylic)

## Run netSEM

  ans_acrylic <- netSEMm(acrylic)

## Subset dataset

  res <- subsetData(ans_acrylic,cutoff = c(0.3,0.6,0.8))

## Plot the network model with adjusted-R-squred of c(0.3,0.6,0.8)

  plot(ans_acrylic,res)

# Lots look into the netSEM::plot function
  
  ?netSEM::plot.netSEM

## Or remove the less significant relationships

  plot(ans_acrylic,res,style = FALSE)

## Summary

  summary(ans_acrylic)

## Extract relations between IrradTot and IAD2

  cf_acrylic <- path(ans_acrylic,from = "IAD2",to = "IrradTot")

  print(cf_acrylic)

## Print three components of the result

  ans_acrylic$table

  ans_acrylic$bestModels

  ans_acrylic$allModels

#=======================================================================
# Exmaple PET 
#
# First lets clar our environment so that our moels don't get mixed


  rm(list = ls())

# Lets look at the pet vignette

  vignette("pet",package = "netSEM") 

# netSEM Modeling of the Weathering Driven Degradation of 
# Poly(ethylene-terephthalate) Films

## Load the PET data set

  data(pet)

## Run netSEM

  ans_pet <- netSEMm(pet)

## Subset dataset with three cutoff

  res_pet <- subsetData(ans_pet,cutoff = c(0.3,0.6,0.8))

## Plot the network model 

  plot(ans_pet,res_pet)

# Network diagram for data
##  "YI" is the endogenous and all other variables are considered as exogenous. 

  plot(ans_pet,res_pet,style = FALSE)

# Use pathwayRMSE to examine errors of network paths

  pathwayRMSE(ans_pet)

# License: CC-BY-SA 4.0
#
  browseURL("https://creativecommons.org/licenses/by-sa/4.0/")
  